version: '3.8'

services:
  uniapplication:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    restart: unless-stopped
    container_name: uniapplication
    environment:
      - TZ=Europe/Rome
      - PORT=3001

