version: '3.8'

services:
  uniapplication:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    restart: unless-stopped
    container_name: uniapplication
    environment:
      - TZ=Europe/Rome
      - PORT=3001
      - HOSTNAME=0.0.0.0
